version: '3.8'

networks:
  ceres-dev:
    external: true

services:
  pytiler:
    build: .
    env_file: .env
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8889:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    networks:
      - default
      - ceres-dev